### ISSUE TITLE
New compression method used by SuperSplat is not compatible

### ISSUE THREAD

**Issue by murcje** [mkkellogg/GaussianSplats3D#387]
Hi!

Recently, PlayCanvas introduced support for Spherical Harmonics up to level 3 in a new compressed .ply format (in their SuperSplaat application). However, I’ve noticed that this new format is currently incompatible with your viewer.

The updated .ply files seem to include additional data for the spherical harmonics, and I suspect this may be why they fail to render correctly. 

I will provide example .ply files if that could help in assessing what updates might be needed. 

https://we.tl/t-5AkeziLorp

Please let me know if I can assist further.

Best regards,

Marc

**Comment by seppestaes** [comment]
Hi, 

Just wondering, why would you need it to be compatible with the compressed format of SuperSplat? To use it as an intermediate editor? 

Grtz

**Comment by murcje** [comment]
Hi,

We have used SuperSplat extensively to clean up and compress splats to compressed .ply, a format that does a factor 15 compression. We then deploy these splats on our platform that makes use of this webviewer. Works great!

They have recently updated their compression to include SH3. In SuperSplat you can set the displayed SH to 0-3, and when you export a splat it will export the amount of SH bands that you selected for display. When I set it to 0, I get the same compression ratio as before (filesize is about the same). But when I view that through this webviewer, the colors are off. See examples below:

![image](https://github.com/user-attachments/assets/1da72d13-6b0c-40bc-9aef-fa242dd109c5)
![image](https://github.com/user-attachments/assets/5e32f179-27f1-4ba7-a993-ea3d237fa788)

**Comment by seppestaes** [comment]
SH3 is mentioned in one of the comments, on the roadmap, but not a priority, I believe. Out of interest, your results look excellent with SH 0-2, do you see a substantial difference in quality with SH3?

**Comment by murcje** [comment]
@seppestaes Thanks, these are both SH0. I notice some difference when viewing with more SH (in SuperSplat), but for large scenes like landscapes I don't see a huge increase in fidelity, it's just a tiny bit more rich/detailed in colors it seems to me.

Here are the (SH0) scenes:

old compressed .ply: https://voluma.ai/edit/voluma/real_estate/re1c
new compressed .ply: https://voluma.ai/view/voluma/real_estate/re1

I had some communication with the devs of Playcanvas (SuperSplat) and they mentioned this:

At the time we added support for SH we also made a small change to the way colors are stored. Colors were just clamped 0..1 previously, but now we store a per-chunk min.rgb and max.rgb in order to support HDR colors.

**Comment by seppestaes** [comment]
@murcje Nice result/integration! Thanks for the update. You're using PlayCanvas' compressed ply / splat and not @mkkellogg's .ksplat?

**Comment by murcje** [comment]
@seppestaes Usually we do use .ply. They are even smaller in size then ksplat. We do use ksplat when we need a nice reveal of the splat, they are better structured and work better for that purpose.

**Comment by mkkellogg** [comment]
I have branch with a fix for the incorrect colors being read from the compressed playcanvas `.ply` here: https://github.com/mkkellogg/GaussianSplats3D/tree/playcanvas_incorrect_colors. It doesn't yet incorporate any additional SH bands from their updated format -- that will be next on my list.

**Comment by mkkellogg** [comment]
@murcje I updated the https://github.com/mkkellogg/GaussianSplats3D/tree/playcanvas_incorrect_colors branch to support spherical harmonics from compressed playcanvas `.ply` files (up to degree 2). Would you be interested in testing it out? I have done some preliminary testing on my end and it seems to work correctly.

**Comment by murcje** [comment]
@mkkellogg thank you, as soon as my collegue is back from his holiday we will test this out. Probably next week.

Happy holidays!

**Comment by mkkellogg** [comment]
Sounds good, happy holidays to you too!

**Comment by seppestaes** [comment]
Hi,

Did one test with a SuperSplat compressed ply on https://github.com/mkkellogg/GaussianSplats3D/tree/playcanvas_incorrect_colors

when set to SH0 and SH2, it renders nicely, SH1 gives distorted colors here

**Comment by mkkellogg** [comment]
Ok, it looks like there was a bug with my viewer that manifested when viewing any small scene with only 1st degree spherical harmonics. @seppestaes I pushed a fix, want to give ti a try?

**Comment by seppestaes** [comment]
Hi @mkkellogg , I tried on playcanvas_incorrect_colors, for the moment still the same result for SH1. Thanks for looking into this, not using SuperSplat myself, but all my splats have less than 1M.

**Comment by meditation-error** [comment]
Collegue of @murcje here: I tested with the [playcanvas_and_spz_compression](https://github.com/mkkellogg/GaussianSplats3D/tree/playcanvas_and_spz_compression) branch and the use of the latest supersplat exports seems to work fine now! (I tested SH0 & SH2 splats)

**Comment by mkkellogg** [comment]
These updates are now in the latest release: [v0.4.7](https://github.com/mkkellogg/GaussianSplats3D/releases/tag/v0.4.7)
